config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root 'posts#index', as: 'home'

	get 'about' => 'pages#about' , as: 'about'
 	get 'avtorun' => 'avtorun#avtorizate', as: 'avt'

    resources :posts do 
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
 	validates :username, presence: true, length: {minimum: 5}
end

app/models/post.rb
class Post < ApplicationRecord
	has_many :comments
 	validates :title, presence: true, length: {minimum: 5}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/avtorun_controller.rb
class AvtorunController < ApplicationController
	def avtorizate
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
    @comment = Post.find(params[:id])

    @comment.destroy
    redirect_to posts_path
  end

  private def comment_params
    params.require(:comment).permit(:username, :body)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	def about
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index 
    @post =Post.all
  end

  def new
    @post = Post.new
  end

  def show 
    @post = Post.find(params[:id]) 
  end

  def edit 
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if(@post.update(post_params))           
    redirect_to @post        
   else                      
    render 'edit'             
    end
  end

  def destroy
    @post = Post.find(params[:id])

    @post.destroy
    redirect_to posts_path
  end

  def create
    @post = Post.new(post_params)

    if(@post.save)           
    redirect_to @post        
   else                      
    render 'new'             
   end
  end

  private def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/avtorun_helper.rb
module AvtorunHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/avtorun/avtorizate.html.erb
 <form class="form-signin">
  <img class="mb-4" src="/docs/4.3/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72">
  <h1 class="h3 mb-3 font-weight-normal">Пожалуйста войдите</h1>
  <label for="inputEmail" class="sr-only">Email address</label>
  <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>
  <label for="inputPassword" class="sr-only">Password</label>
  <input type="password" id="inputPassword" class="form-control" placeholder="Password" required>
  <div class="checkbox mb-3">
    <label>
      <input type="checkbox" value="remember-me"> Remember me
    </label>
  </div>
  <button class="btn btn-lg btn-primary btn-block" type="submit">Войти</button>
  <p class="mt-5 mb-3 text-muted">&copy; 2017-2019</p>
</form>

app/views/layouts/application.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Pogiloy
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .d-flex.w-100.h-100.p-3.mx-auto.flex-column
      .d-flex.flex-column.flex-md-row.align-items-center.p-3.px-md-4.mb-3.colorb.shadow-sm
        %h5.my-0.mr-md-auto.font-weight-bolt= link_to 'ITproject', home_path
        %span.p-2.text-dark
          = link_to "Создание поста", new_post_path
        %span.p-2.text-dark
          = link_to "Авторизация", new_user_session_path
        %span.p-2.text-dark
          = link_to "Регистрация", new_user_registration_path
      .cover-container.d-flex.w-100.h-100.p-3.mx-auto.flex-column.cover-container.d-flex.w-100.h-100.p-3.mx-auto.flex-column.fl
        = yield

app/views/pages/about.haml
%p Разнообразный и богатый опыт начало повседневной работы по формированию позиции способствует подготовки  и реализации позиций, занимаемых участниками в отношении поставленных задач. Не следует, однако забывать, что консультация с широким активом требуют от нас анализа направлений прогрессивного развития. Равным образом начало повседневной работы по формированию позиции обеспечивает широкому кругу (специалистов) участие в формировании новых предложений. Не следует, однако забывать, что сложившаяся структура организации позволяет оценить значение направлений прогрессивного развития. Задача организации, в особенности же начало повседневной работы по формированию позиции играет важную роль в формировании соответствующий условий активизации.

%p Значимость этих проблем настолько очевидна, что укрепление и развитие структуры влечет за собой процесс внедрения и модернизации новых предложений. Повседневная практика показывает, что постоянный количественный рост и сфера нашей активности в значительной степени обуславливает создание системы обучения кадров, соответствует насущным потребностям. Значимость этих проблем настолько очевидна, что постоянный количественный рост и сфера нашей активности требуют определения и уточнения позиций, занимаемых участниками в отношении поставленных задач.

app/views/pages/about.html.haml
%p Разнообразный и богатый опыт начало повседневной работы по формированию позиции способствует подготовки  и реализации позиций, занимаемых участниками в отношении поставленных задач. Не следует, однако забывать, что консультация с широким активом требуют от нас анализа направлений прогрессивного развития. Равным образом начало повседневной работы по формированию позиции обеспечивает широкому кругу (специалистов) участие в формировании новых предложений. Не следует, однако забывать, что сложившаяся структура организации позволяет оценить значение направлений прогрессивного развития. Задача организации, в особенности же начало повседневной работы по формированию позиции играет важную роль в формировании соответствующий условий активизации.

%p Значимость этих проблем настолько очевидна, что укрепление и развитие структуры влечет за собой процесс внедрения и модернизации новых предложений. Повседневная практика показывает, что постоянный количественный рост и сфера нашей активности в значительной степени обуславливает создание системы обучения кадров, соответствует насущным потребностям. Значимость этих проблем настолько очевидна, что постоянный количественный рост и сфера нашей активности требуют определения и уточнения позиций, занимаемых участниками в отношении поставленных задач.

app/views/posts/edit.haml
- if user_signed_in?
  %h4 Добавление нового поста
  = form_for :post ,url: posts_path do |f|
    - if @post.errors.any?
      - @post.errors.full_messages.each do |msg|
        .alert.alert-danger= msg
    %p
      Название статьи
      %br/
      = f.text_field(:title, {:class => 'form-control'})
    %p
      Текс статьи
      %br/
      = f.text_area(:body, {:class => 'form-control'})
    %p
      = f.submit ({:class => 'btn btn-success'})

app/views/posts/index.haml
%h1 Все статьи
- @post.each do |post|
  .aler.aler-light
    %h3= post.title
    %p= post.body
    = link_to "Читать далее", post_path(post), :class => ' btn btn-info'

app/views/posts/new.haml
- if user_signed_in?
  %h4 Добавление нового поста
  = form_for :post ,url: posts_path do |f|
    - if @post.errors.any?
      - @post.errors.full_messages.each do |msg|
        .alert.alert-danger= msg
    %p
      Название статьи
      %br/
      = f.text_field(:title, {:class => 'form-control'})
    %p
      Текс статьи
      %br/
      = f.text_area(:body, {:class => 'form-control'})
    %p
      = f.submit ({:class => 'btn btn-success'})

app/views/posts/show.haml
%h1= @post.title
%p= @post.body
%hr/
= link_to 'Редактировать', edit_post_path(@post), :class => 'btn btn-warning'
= link_to 'Удалить пост', post_path(@post), method: :delete, data:{confirm: "Вы точно хотите удалить пост?"},:class =>'btn btn-danger'
%hr/
%h2
  Все коментарии
  - @post.comments.each do |comment|
    .aler.aler-light
      %p
        %strong>= comment.username
        \: #{comment.body}
          = link_to "del",post_comments_path(@post,comment.id) ,method: :delete, class => 'btn-btn-danger'
  %hr/
  %h4 Коментарии
  = form_for([@post,@post.comments.build]) do |f|
    %p
      Пользователь
      %br/
      = f.text_field(:username, {:class => 'form-control'})
    %p
      Текс коментария
      %br/
      = f.text_area(:body, {:class => 'form-control'})
    %p
      = f.submit ({:class => 'btn btn-warning'})